# biz_server.toml

ver = "0.0.1"
#logPath = "/tmp/frontend.log"
serverId = 1

[server80.server]
name = "frontend80"
protoName = "mtproto"
addr = "0.0.0.0:8800"
# 80

[server80.discovery]
serviceName = "frontend80"
nodeID = "node1"
rPCAddr = "127.0.0.1:10000"
etcdAddrs = ["http://127.0.0.1:2379"]
interval = "2s"
tTL = "10s"

[server443.server]
name = "frontend443"
protoName = "mtproto"
addr = "0.0.0.0:12345"
# 43

[server443.discovery]
serviceName = "frontend443"
nodeID = "node1"
rPCAddr = "127.0.0.1:10000"
etcdAddrs = ["http://127.0.0.1:2379"]
interval = "2s"
tTL = "10s"

[server5222.server]
name = "frontend5222"
protoName = "mtproto"
addr = "0.0.0.0:5222"
# 5222

[server5222.discovery]
serviceName = "frontend5222"
nodeID = "node1"
rPCAddr = "127.0.0.1:10000"
etcdAddrs = ["http://127.0.0.1:2379"]
interval = "2s"
tTL = "10s"

[clients]
    [[clients.clients]]
    name = "handshake"
    protoName = "brpc"
    etcdAddrs = ["http://127.0.0.1:2379"]
    addrList = ["127.0.0.1:10005"]
    balancer = "random"

    [[clients.clients]]
    name = "session"
    protoName = "brpc"
    etcdAddrs = ["http://127.0.0.1:2379"]
    addrList = ["127.0.0.1:10000"]
    balancer = "ketama"
