# sync_server.toml

ver = "0.0.1"
#logPath = "/tmp/biz_server.log"
serverId = 1

[server]
addr = "0.0.0.0:10002"

[server.rpcDiscovery]
serviceName = "sync2"
nodeID = "node1"
rPCAddr = "127.0.0.1:10002"
etcdAddrs = ["http://127.0.0.1:2379"]
interval = "2s"
tTL = "10s"

[sessionClient]
    [[sessionClient.clients]]
    name = "session"
    protoName = "zproto"
    etcdAddrs = ["http://127.0.0.1:2379"]
    addrList = ["127.0.0.1:10000"]
    balancer = "round_robin"

[[redis]]
name = "cache"
addr = "127.0.0.1:6379"
idle = 100
active = 100
dialTimeout = "1s"
readTimeout = "1s"
writeTimeout = "1s"
idleTimeout = "10s"
dbNum = "0"
password = ""

[[mysql]]
name = "immaster"
dsn = "root:@tcp(127.0.0.1:3306)/chatengine?charset=utf8mb4"
active = 5
idle = 2

[[mysql]]
name = "imslave"
dsn = "root:@tcp(127.0.0.1:3306)/chatengine?charset=utf8mb4"
active = 5
idle = 2
